LOOP-1486: add suspend threshold information screen + editor
tidepool-org/LoopKit pull request #135
Opened 2020-07-10 14:35 UTC by novalegra

https://tidepool.atlassian.net/browse/LOOP-1486

2020-07-10 16:57 UTC, novalegra commented on LoopKit/TherapySettings.swift
> +public struct TherapySettings: Equatable, Codable {
These changes are to enable `TherapySettings` to be a subcomponent of a prescription

2020-07-13 12:17 UTC, nhamming approved these changes
LGTM

2020-07-13 12:17 UTC, nhamming commented on LoopKitUI/Views/Settings Editors/SuspendThresholdEditor.swift
> +        Text("When your glucose is predicted to go below this value, the app will recommend a basal rate of 0 U/h and will not recommend a bolus.", comment: "Suspend threshold description")
[nit] elsewhere `LocalizedString` is being used.

2020-07-13 19:57 UTC, rickpasetto requested changes
I have one requested fix...but other than that LGTM!

2020-07-13 19:57 UTC, rickpasetto commented on LoopKit/TherapySettings.swift
>          self.preMealTargetRange = preMealTargetRange
I had fixed this in my branch: workoutTargetRange is never initialized. O_o.  (I realize this is somewhat orthogonal to _this_ PR)
```suggestion
        self.preMealTargetRange = preMealTargetRange
        self.workoutTargetRange = workoutTargetRange
```

2020-07-13 20:15 UTC, novalegra commented
> I have one requested fix...but other than that LGTM!

Done - thanks for catching that!

2020-07-13 20:31 UTC, rickpasetto approved these changes
LGTM

2020-07-13 20:33 UTC, merged