Adds a Cartfile target to LoopKit
tidepool-org/LoopKit pull request #283
Opened 2020-11-20 23:09 UTC by rickpasetto

A few months ago SwiftCharts was added as a Carthage dependency to LoopKit.  This target ensures carthage bootstrap gets run before the build.

2020-11-20 23:39 UTC, darinkrauss requested changes
One change needed.

2020-11-20 23:39 UTC, darinkrauss commented on LoopKit.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = 75U4X84TEG;
Please remove `DEVELOPMENT_TEAM` here and below. Thanks!

2020-11-21 00:33 UTC, rickpasetto commented
@darinkrauss I made a few more changes than one :).  I also fixed the CI script and added caching to it.

2020-11-21 00:52 UTC, darinkrauss approved these changes
LGTM! 🚀

2020-11-21 01:09 UTC, merged