[LOOP-2385] therapy settings unit is fixed to mg/dL
tidepool-org/LoopKit pull request #333
Opened 2021-03-09 16:05 UTC by nhamming

https://tidepool.atlassian.net/browse/LOOP-2385

In an effort to break up this work and review, this code just fixes the therapy settings unit to `mg/dL

*2 reviews please

2021-03-09 17:48 UTC, rickpasetto commented
@nhamming I'm confused. Why do this instead of changing those `DoubleRange` values to `ClosedRange<HKQuantity>`?  Don't we do that elsewhere?

2021-03-09 17:48 UTC, rickpasetto reviewed
See my comment...

2021-03-10 13:06 UTC, nhamming commented
Thanks @darinkrauss for the discussion. After some more thought, I made this update. Please let me know if this addresses your concern. Also see https://github.com/tidepool-org/Loop/pull/373 for related updates in Loop. 

If you are good, I'll request a second review from Rick.

2021-03-10 18:03 UTC, darinkrauss requested changes
Mostly LGTM, but I believe you should explicitly add the units into the encoded `TherapySettings` and use those while decoding.

2021-03-10 18:03 UTC, darinkrauss commented on LoopKit/TherapySettings.swift
> +        .milligramsPerDeciliter
I'm confused. We are forcing `TherapySettings` to always use `mg/dL`?

2021-03-10 18:03 UTC, darinkrauss commented on LoopKit/TherapySettings.swift
> +    fileprivate static let codingGlucoseUnit: HKUnit = .milligramsPerDeciliter
I believe you should include the units in the encoded data and the read and use that when decoding (rather than assuming the coding units on decoding). This will be used outside of the Loop app proper (critical event log export and upload to Tidepool backend) so being explicit about what units were used during encoding is important.

2021-03-10 18:03 UTC, darinkrauss commented on LoopKit/TherapySettings.swift
> +    fileprivate static let codingGlucoseUnit: HKUnit = .milligramsPerDeciliter
BTW, it's okay to have this constant, but use it for encoding only.

2021-03-10 18:03 UTC, darinkrauss commented on LoopKit/TherapySettings.swift
> +    fileprivate static let codingGlucoseUnit: HKUnit = .milligramsPerDeciliter
Oh, and make the units a *required* property during decoding.

2021-03-10 19:17 UTC, rickpasetto approved these changes
LGTM, though I agree with @darinkrauss 's comment about encoding the unit...

2021-03-10 19:17 UTC, rickpasetto commented on LoopKit/TherapySettings.swift
> +    public init(from decoder: Decoder) throws {
Bummer that you had to do this by hand.  Thanks for doing it!

2021-03-10 20:05 UTC, darinkrauss requested changes
Two small changes for consistency in encoding/decoding the blood glucose unit.

2021-03-10 20:05 UTC, darinkrauss commented on LoopKit/TherapySettings.swift
> +        case codingGlucoseUnitString
Sorry, I would just call this `.bloodGlucoseUnit` in the encoded data to be consistent with `StoredSettings` above.

2021-03-10 20:05 UTC, darinkrauss commented on LoopKit/SettingsStore.swift
> +                  preMealTargetRange: try container.decodeIfPresent(DoubleRange.self, forKey: .preMealTargetRange)?.quantityRange(for: bloodGlucoseUnit ?? StoredSettings.codingGlucoseUnit),
I would make `bloodGlucoseUnit` a required property of the encoded/decoded data.

So, a few lines above (line 265-268), change:
```
        var bloodGlucoseUnit: HKUnit?
        if let bloodGlucoseUnitString = try container.decodeIfPresent(String.self, forKey: .bloodGlucoseUnit) {
            bloodGlucoseUnit = HKUnit(from: bloodGlucoseUnitString)
        }
```
to something like:
```
       let bloodGlucoseUnit = HKUnit(from: try container.decode(String.self, forKey: .bloodGlucoseUnit))
```

And, in the `encode` function below, change:
```
        try container.encodeIfPresent(bloodGlucoseUnit?.unitString, forKey: .bloodGlucoseUnit)
```
to something like:
```
        try container.encode((bloodGlucoseUnit ?? StoredSettings.codingGlucoseUnit).unitString, forKey: .bloodGlucoseUnit)
```
Does that make sense?

2021-03-11 17:34 UTC, darinkrauss approved these changes
LGTM! 🚀

2021-03-12 17:26 UTC, merged