LOOP-1114: adds Version Checking to the responsibilities of `SupportUI` [plugins]
tidepool-org/LoopKit pull request #408
Opened 2021-10-15 20:42 UTC by rickpasetto

After a few rounds of implementation, we settled on having the existing `SupportUI` plugin interface support the ability to do version checking.  So, now it has the responsibilities to:
- Do a version check with whatever "service" it needs to to determine if a new version of the host app is available
- Provide a UI screen to explain to the user what kind of update it is (from **Settings**)
- Provide a menu item (like it did before) for Support

2021-10-18 16:33 UTC, darinkrauss requested changes
A few changes needed here.

2021-10-18 16:33 UTC, darinkrauss commented on LoopKitUI/SupportUI.swift
> +    func setAlertIssuer(alertIssuer: AlertIssuer?)
This seems non-standard. The pump and CGM managers use a delegate as the alert issuer plus they are `AlertResponder`s.

2021-10-18 16:33 UTC, darinkrauss commented on LoopKitUI/SupportUI.swift
> +    func softwareUpdateView(guidanceColors: GuidanceColors,
[nit] I would put `guidanceColors` last as it is the least relevant to this particular view.

2021-10-18 16:33 UTC, darinkrauss commented on LoopKitUI/SupportUI.swift
> +                            openAppStoreHook: (() -> Void)?
[nit] "Hook"?

2021-10-18 16:33 UTC, darinkrauss commented on LoopKitUI/SupportUI.swift
> +    ) -> AnyView?
Do we really want to be passing SwiftUI through these protocols? We don't do that anywhere else, AFAIK.

2021-10-18 16:33 UTC, darinkrauss commented on MockKit/MockCGMManager.swift
> +    private let lockedMockSensorState = Locked(MockCGMState(isStateValid: true))
These changes look like there are for https://tidepool.atlassian.net/browse/LOOP-3884. Consider a different PR or, at the very minimum, reference this ticket in the commits and PR.

2021-10-18 16:33 UTC, darinkrauss commented on MockKitUI/View Controllers/MockServiceTableViewController.swift
>  fileprivate extension VersionUpdate {
This should probably be elsewhere if you just removed all of the other update related code from the `MockServiceTableViewController`.

2021-10-18 16:33 UTC, darinkrauss commented on MockKitUI/MockSupport.swift
> +                                         acknowledgeActionButtonLabel: NSLocalizedString("OK", comment: "default acknowledgement"),
[nit] Capitalize first word of comment.

2021-10-18 16:33 UTC, darinkrauss commented on MockKitUI/MockSupport.swift
> +                                         acknowledgeActionButtonLabel: NSLocalizedString("OK", comment: "default acknowledgement"),
[nit] Capitalize first word of comment.

2021-10-18 16:33 UTC, darinkrauss commented on MockKitUI/MockSupport.swift
> +        alertIssuer!.issueAlert(Alert(identifier: alertIdentifier, foregroundContent: alertContent, backgroundContent: alertContent, trigger: .immediate))
If `alertIssuer` is optional (see `setAlertIssuer(alertIssuer: AlertIssuer?)`), then should we really force it here? Either make `alertIssuer` required or make this `alertIssuer?`.

2021-10-18 16:33 UTC, darinkrauss commented on MockKitUI/MockSupport.swift
> +            case .required: return ActionSheet.Button.destructive(Text(versionUpdate.localizedDescription), action: setter)
I'm am not a fan of having the statement on the same line as the case (I find it much easier to miss the statement being executed), but I can deal with it when it is trivial code. This, however, is not trivial, so please move to separate lines. And, really, what exactly are you saving here by putting them on the same line?

2021-10-20 17:59 UTC, rickpasetto commented on LoopKitUI/SupportUI.swift
> +    func setAlertIssuer(alertIssuer: AlertIssuer?)
Yeah I am not sure I would call that a standard.  That was adding Alerting to the plugins within the existing plugin framework.  I'll follow that pattern, though, as you suggest. (TBH I prefer `AlertIssuer`.  It is a clearer name & responsibility than just `SupportUIDelegate`)

2021-10-20 18:04 UTC, rickpasetto commented on LoopKitUI/SupportUI.swift
> +    func softwareUpdateView(guidanceColors: GuidanceColors,
It's a Swift standard to put function blocks parameters last in functions if possible.  But I will put it before that.

2021-10-20 18:07 UTC, rickpasetto commented on LoopKitUI/SupportUI.swift
> +                            openAppStoreHook: (() -> Void)?
I'll remove

2021-10-20 18:09 UTC, rickpasetto commented on LoopKitUI/SupportUI.swift
> +    ) -> AnyView?
Why not?  I see this as an opportunity to move towards SwiftUI... other "ManagerUI" protocols return UIKit ViewControllers.  What's the down side?

2021-10-20 18:10 UTC, rickpasetto commented on MockKit/MockCGMManager.swift
> +    private let lockedMockSensorState = Locked(MockCGMState(isStateValid: true))
A separate PR has been merged

2021-10-20 18:29 UTC, darinkrauss commented on LoopKitUI/SupportUI.swift
> +    ) -> AnyView?
Probably nothing, but you should get @ps2's take on it.

2021-10-20 20:41 UTC, ps2 commented on LoopKitUI/SupportUI.swift
> +    ) -> AnyView?
I don't see a problem with this, per se. The only nit I see is that you have to use AnyView, but this isn't a blocker.

2021-10-21 23:05 UTC, darinkrauss approved these changes
LGTM!

2021-10-21 23:05 UTC, darinkrauss commented on LoopKitUI/SupportUI.swift
> +public protocol SupportUIDelegate: AlertIssuer {
[nit] Collapse into one line?

2021-10-22 19:21 UTC, merged