UI/LOOP-935/Calibration-view
tidepool-org/LoopKit pull request #45
Opened 2020-01-17 12:29 UTC by nhamming

https://tidepool.atlassian.net/browse/LOOP-935

extensions to support Dexcom UI updates.

2020-01-20 21:12 UTC, darinkrauss approved these changes
Only one *really* minor nit/thought. LGTM. :shipit:

2020-01-20 21:12 UTC, darinkrauss commented on LoopKitUI/Views/TableViewTitleLabel.swift
> +        font = UIFont.titleFontGroupedInset
[nit] Perhaps a common `initFonts` function?

2020-01-21 17:34 UTC, darinkrauss approved these changes
LGTM 🚀

2020-01-21 18:21 UTC, ps2 requested changes
We need to be able to respond to dynamic type in our interfaces for accessibility.

2020-01-21 18:21 UTC, ps2 commented on LoopKitUI/Extensions/UIFont.swift
> +        return UIFont.systemFont(ofSize: 28, weight: UIFont.Weight.semibold)
This does not respond to dynamic type. Perhaps take a look at https://developer.apple.com/documentation/uikit/uifont/1619030-preferredfont

2020-01-21 21:17 UTC, mpangburn approved these changes
LGTM!

2020-01-22 12:46 UTC, merged