Noah/loop 4682 favorite foods
tidepool-org/LoopKit pull request #534
Opened 2023-08-10 18:03 UTC by SwiftlyNoah

https://tidepool.atlassian.net/browse/LOOP-4682
Goes with:
https://github.com/tidepool-org/LoopConfigurator/pull/18
https://github.com/tidepool-org/Loop/pull/587

-`StoredFavoriteFood` struct that allows storage of favorite foods
- Added new Row views that are used in both `CarbEntryView` and `AddEditFavoriteFoodView`
  - At most one `Row` can be focused at a time
- Design updates: `FavoriteFoodCardView` --> `FavoriteFoodListRow`
- New `FavoriteFoodDetailView` for viewing (and deleting) favorite foods
- Moved some now unused UIKit code to a legacy folder in LoopKitUI/CarbKit (not sure if the files should be deleted)

2023-08-10 22:20 UTC, ps2 requested changes
Looking nice! I just have a localization request, and a suggestion.

2023-08-10 22:20 UTC, ps2 commented on LoopKit/FavoriteFood/FavoriteFood.swift
> +    public var absorptionTimeString: String {
Generally we should be using system formatters to support localization. Please update to support localization in some way; either by using a system formatter (preferred) or making the format strings translatable via `LocalizedString()`

2023-08-10 22:20 UTC, ps2 commented on LoopKit/FavoriteFood/FavoriteFood.swift
> +        guard let string = QuantityFormatter(for: unit).string(from: carbsQuantity) else {
Instantiating formatters for each string can add a lot of overhead; we usually have string generation as part of the view layer, so either in the view, or in the view model.

2023-08-10 22:20 UTC, ps2 commented on LoopKitUI/CarbKit/AbsorptionTimePickerRow.swift
> +public struct AbsorptionTimePickerRow<Row: Equatable>: View {
This `Row` system is unusual.  I see that you're using it to track which row(s) are expanded and which are collapsed. 

I'm wondering if it might be simpler if the state for each row's expanded/collapsed state could just be stored on the parent view as a simple state var, like `@State private var absorptionTimeRowExpanded: Bool`, and pass it in as a binding to each row.  Just an idea; won't block on this.

2023-08-10 22:20 UTC, ps2 commented on LoopKitUI/CarbKit/AbsorptionTimePickerRow.swift
> +public struct AbsorptionTimePickerRow<Row: Equatable>: View {
Behavior like collapsing other rows when a new row is expanded can managed in the parent view, and this view doesn't need to be aware of the notion of a row id.

2023-08-11 15:00 UTC, SwiftlyNoah commented on LoopKit/FavoriteFood/FavoriteFood.swift
> +        guard let string = QuantityFormatter(for: unit).string(from: carbsQuantity) else {
I moved the carb quantity formatter and made a new absorption time formatter in Loop/Loop/ViewModels/FavoriteFoodsViewModel :)

2023-08-11 15:00 UTC, SwiftlyNoah commented on LoopKitUI/CarbKit/AbsorptionTimePickerRow.swift
> +public struct AbsorptionTimePickerRow<Row: Equatable>: View {
Good point, I made that code a bit more confusing than it needed to be!

2023-08-12 13:23 UTC, ps2 approved these changes
Thanks for the updates!  Looking good.  Two more things: any code that is truly unused should be removed, and any types that are not not dependencies of other LoopKit code, and are not used by code outside the Loop repo, should probably be moved up to Loop itself. LoopKit should be reserved for things that need to be shared with plugins or that are used by other shared components.

2023-08-14 14:09 UTC, merged